modLoader = "javafml"
loaderVersion = "[4,)"
license = "FIXME"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

# FIXME - remove this if you don't want the architectury api
[[dependencies.${modId}]]
modId = "architectury"
type = "required"
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"
